backend:
  name: git-gateway
  branch: master

display_url: https://nielsbik.nl
media_folder: static/assets/images
public_folder: /assets/images

collections:
  - name: work
    label: Work
    label_singular: Project
    folder: src/pages/projects
    create: true
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    fields:
      - name: templateKey
        label: Template key
        widget: hidden
        default: project-page
      - name: date
        label: Publish date
        widget: datetime
      - name: title
        label: Title
        widget: string
      - name: banner
        label: Banner
        widget: image
      - name: thumb
        label: Thumbnail
        widget: image
      - name: source
        label: Source
        widget: string
        required: false
      - name: url
        label: URL
        widget: string
        required: false
      - name: body
        label: Body
        widget: markdown
  - name: blog
    label: Blog
    label_singular: Post
    folder: src/pages/blog
    create: true
    extension: md
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - name: templateKey
        label: Template key
        widget: hidden
        default: blog-post
      - name: title
        label: Title
        widget: string
      - name: date
        label: Publish date
        widget: datetime
      - name: banner
        label: Banner
        widget: image
      - name: body
        label: Body
        widget: markdown
